#ifndef ARBITER_DIALECT_ARBITER_ARBITERDIALECT_H
#define ARBITER_DIALECT_ARBITER_ARBITERDIALECT_H

#include "arbiter/Dialect/Arbiter/IR/ArbiterDialect.h"

#endif // ARBITER_DIALECT_ARBITER_ARBITERDIALECT_H
